### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [zio-tt/mirai_select#141]
MVPリリースお疲れ様でした。
挙動を確認しました。LGTMです。
一定の技術力に達しているかと思います。
以下の改善案を元にブラッシュアップをしていきましょう。

■改善案
●描画の最適化
a.みんなの投稿表示→自分の投稿表示した際に、他の方の投稿も削除できてしまいました。こちらは早めに調整を行うべきかと感じました。（優先度：高）
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/4d1d3c88917119db80b4f2295eddb254.gif)](https://startup-technology.gyazo.com/4d1d3c88917119db80b4f2295eddb254)

b.テキストを投稿した際に、別ブラウザにそれが反映されるまでのタイミングが都度異なっていたのが少し気になりました。（対応の優先度でいうとかなり低くて良いかと。理由：ブラウザを並べて確認する人は少ないだろうという考えから）
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/dc5d475c126747f1e2c0f26cdbc6363a.gif)](https://startup-technology.gyazo.com/dc5d475c126747f1e2c0f26cdbc6363a)

●文言・背景色
c.`トークン`という文字列で表現されていますが、あまり馴染みの無いユーザーもいるかと思うので、一般的なポイントやクレジットといった文言の方が良いかと思いました。

d.全体的にオレンジ色の背景になっていますが、天使・悪魔を使ったこのサービスの場合、もっと単色背景での統一ではない形もありなのかと思いました。もしオレンジ色での統一感に意図があれば変更は不要ですが、もう少し世界観を出すように拘っても良いかと感じました。

●その他
e.AIに相談できる文言ですが、50文字ではちょっと足りないケースもあるのかなと感じました。精度などの観点から50文字が最適であるのなら致し方ないですが、もう少し入力できると対応の幅も広がるのではないかと。（優先度：低）

---

上記のレビューをタスクに落とし込み、issueに書きましたら、下記URLのように1週間毎に列を作成して、そこにissueを配置していってください。こちらのissueは対応が済みましたらcloseしていただいて大丈夫です。

https://github.com/users/Tsuchiya2/projects/2/views/1

また書き出したissueをもとに修正完了までのスケジュール、本リリースの目処を教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by zio-tt** [comment]
レビューありがとうございます。

頂いたレビューを元にissueを作成しましたのでご確認の程よろしくお願いいたします。
https://github.com/users/zio-tt/projects/6

修正は1/27までを目処に行います。
特に描画の最適化とコメントの反映は重めに考えています。
コメントの反映はWebSocketを検討していますが、期間内に問題が解決できそうにない場合はSWRというライブラリを使用してポーリングしようと思います。

本リリースは2/11を目処に開発します。
もし早めにタスクが終わりそうであれば「If possible」の項目に着手します。

以上、ご確認の程よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
ありがとうございます！
引き続き頑張ってください。

**Comment by Tsuchiya2** [comment]
ありがとうございます！
引き続き頑張ってください。
